### ISSUE TITLE
Last 2~3 chars missing?

### ISSUE THREAD

**Issue by Thermospore** [greduan/kindle-highlights#2]
![image](https://user-images.githubusercontent.com/35350819/152654729-356b275b-b723-4793-b200-44e583a77d3c.png)

![image](https://user-images.githubusercontent.com/35350819/152654735-ff454d5c-3038-4b96-ace1-13fb427d35e4.png)

![image](https://user-images.githubusercontent.com/35350819/152654740-918d3399-d8c3-443f-a580-69d6761b460b.png)

![image](https://user-images.githubusercontent.com/35350819/152654741-f9d3ca6c-e0c9-4330-b447-e0fa41bae19f.png)

**Comment by greduan** [comment]
Hey, thanks for the report. Sadly this isn't something I can fix. Amazon has an issue with the syncing. For some people it's constant, for others it's more sporadic.

To guard against it you can try to make your selections bigger, then if some chars disappear it's not the ones you wanted..

**Comment by Thermospore** [comment]
Thanks for the info, yea that seems to be a good workaround
